version: "3.8"

services:
  backend:
    build:
      context: ./todo-back
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./todolist
    ports:
      - "3000:3000"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
